### ISSUE TITLE
Assembly in NuGet package is not fully signed.

### ISSUE THREAD

**Issue by L3Z4** [jdevillard/JmesPath.Net#1]
The .Net Framework 4.5 and the dotnet standard 1.6 DLL is not fully signed. This can be validated using 
```Powershell
> sn.exe -vf .\JmesPath.Net.dll
```
This library can be used in a Console Application (tested using a .Net Framework 4.5 and 4.6.1).
It cannot be used in a WebAPI Application,  .Net Framework 4.5 or 4.6.1. The assembly is loaded in a AspNET Core 2.0.

**Comment by jdevillard** [comment]
This seems to be due to a misconfiguration in the project.json where publicSign was set to true.
