### ISSUE TITLE
Target netstandard 2.1

### ISSUE THREAD

**Issue by jmajoor** [jdevillard/JmesPath.Net#100]
The package currently targets netstandard 1.3. Some vulnerability checkers are flagging assemblies that are associated with .netstandard 1.3 as having critical vulnerabilities.

Would it be possible to target .netstandard 2.1?
I could provide a PR if you like and are willing to publish a new version.

**Comment by springcomp** [comment]
Sure that would be helpful.
I‘m not sure which APIs we rely on from netstandard 1.3 though.

We are also considering using multi-targeting to minimize the number of dependencies.

**Comment by jmajoor** [comment]
@springcomp I noticed the dependencies on your gppg and gplex. You want me to add netstandard 2.1 to those (multi-target)?
Because without that, I will still have this 1.3 dependency in my app, just one level down.

**Comment by springcomp** [comment]
@jmajoor  I think there are more recent forks for [GPLEX](https://www.nuget.org/packages/YaccLexTools.Gplex/1.2.2.4#dependencies-body-tab) and [GPPG](https://www.nuget.org/packages/YaccLexTools.Gppg) which are more current as well.
It may be worth pivoting to use these instead.

**Comment by jmajoor** [comment]
I have looked at the suggested packages and the advantage is that those don't have a runtime dependency. However the lexer/parser they generate won't compile with netstandard 1.3, so then it will be netstandard 2.1 and net45.

**Comment by springcomp** [comment]
@jmajoor thanks a lot for looking into this.

Please, do as you see fit.
In the long run, I would probably try to contact the maintainer and have them support multiple runtime output options so that we can abandon our version which, to be honest, I have no business maintaining. I created my versions way back a few years ago when there seemed to be no other options.

**Comment by jmajoor** [comment]
PR #101 includes both the support for netstandard 2.1 and uses [YaccLexTools](https://www.nuget.org/packages/YaccLexTools).

I was able to keep `netstandard1.3` support, though you may want to consider just supporting `net45` and `netstandard2.1`
