### ISSUE TITLE
Nuget package should have addtional metadata

### ISSUE THREAD

**Issue by thompson-tomo** [jdevillard/JmesPath.Net#103]
### Summary
I wish for the nuget packages to have the licence expression property set correctly and the repository url

### Details

The licence expression property should be set to the correct licence type I.e. Apache-2.0 as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc. By providing the repo url it will make it easier to contribute and can be used by source-link.

**Comment by springcomp** [comment]
Please, would you kindly propose a pull-request to that effect ?
Or a [patch or diff](https://stackoverflow.com/questions/40883421/diff-syntax-highlighting-in-github-markdown) expression here as Markdown in this issue ?

**Comment by thompson-tomo** [comment]
All done under #105
