### ISSUE TITLE
Add Net standard 2.1 as TFM

### ISSUE THREAD

**Issue by thompson-tomo** [jdevillard/JmesPath.Net#104]
### Is your feature request related to a problem? Please describe.
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

### Describe the solution you'd like
I want the package to not have an explicit dependency on dependencies which can be provided by the framework ie System.Reflection.TypeExtensions, System.ValueTuple

### Describe alternatives you've considered
Accept the additional dependency

**Comment by springcomp** [comment]
This has [recently been included](https://github.com/jdevillard/JmesPath.Net/pull/101).
We will publish a NuGet package soon.
