### ISSUE TITLE
Add info about `dotnet make`

### ISSUE THREAD

**Issue by StefH** [jdevillard/JmesPath.Net#14]
Please add info to the readme that you need to install the `dotnet make` tool globally to get it compiled.

**Comment by springcomp** [comment]
I believe this not to be true.
Starting from a fresh `git clone` of the repo, the following commands succeed:

    dotnet restore
    dotnet build src/jmespath.net/jmespath.net.csproj

The best proof, is that AppVeyor builds successfully.

**Comment by StefH** [comment]
On my system I could not build using vs2017 because of the dotnet make command in the PrecompileScript step in the csproj.

**Comment by springcomp** [comment]
Can you test with the latest changes to `dotnet-make` available from the latest commit in this repo ?
If that still does not work, please, can you share the output of the commands shown above ?
Please, make sure to remove personally identifiable information from the output.

**Comment by StefH** [comment]
Ok, I've tested on other PC and it seems to work.

Thanks a lot for this library !

I'm going to include this library into this project : https://github.com/WireMock-Net/WireMock.Net , in addition to JsonPath.

JmesPath is much easier to understand and to use.
