### ISSUE TITLE
Compare Dates not working

### ISSUE THREAD

**Issue by lorranpalmeira** [jdevillard/JmesPath.Net#2]
When compare dates example : today >= '2018-07-17T08:00:00Z' not working except today == '2018-07-17T08:00:00Z'.

**Comment by springcomp** [comment]
Thanks for the feedback.
I'm looking into this problem.

**Comment by lorranpalmeira** [comment]
I saw in Python that:
https://github.com/jmespath/jmespath.py/issues/124
