### ISSUE TITLE
'JmesPath.Transform(JToken, string)' is obsolete warning

### ISSUE THREAD

**Issue by Thaina** [jdevillard/JmesPath.Net#20]
https://github.com/jdevillard/JmesPath.Net/blob/fa959fd2585258fcf4ca8dea09163aa6b937af13/src/jmespath.net/JmesPath.cs#L42-L49

https://github.com/jdevillard/JmesPath.Net/blob/355dbefff90e7ce3ceaec14bf3a76936742b7ce5/tools/jmespathnet.compliance/Compliance.cs#L129-L131

These lines just trying to use obsolete function itself. Is it right?

**Comment by springcomp** [comment]
Yes that is right.
We are trying to deprecate using this `Transform` overload, in favour of one that takes a `JToken` instead of a `String`.

**Comment by Thaina** [comment]
@springcomp I mean, it intend to be deprecated but it still being used internally so it caused warning. So I am not sure if it really alright to ignore those warning

**Comment by springcomp** [comment]
You can ignore the warning.
In fact, it is not used internally.
Only the compliance tool uses this overload. But the tool is not a deliverable. Besides, it can easily be adapted, but I just did not take the time to it.

**Comment by hell-racer** [comment]
Hi! We have a case where we need to perform a lot of transformations on the same input, so it looks like if we use string as input it will deserialize it each time… will this negatively impact performance? Thanks!
