### ISSUE TITLE
Remove dependency on Json.NET & enable others

### ISSUE THREAD

**Issue by atifaziz** [jdevillard/JmesPath.Net#24]
I'd like to propose a slight re-architecture of this project to remove the dependency on [Json.NET](https://www.newtonsoft.com/json). It would then allow the project to be used and adapted (in a binary fashion) to other JSON libraries, including (but not limited to) [Jil](https://github.com/kevin-montrose/Jil), [Manatee Json](https://github.com/gregsdennis/Manatee.Json), [Jayrock JSON](https://github.com/atifaziz/Jayrock.Json) and the now system-supplied [System.Text.Json](https://docs.microsoft.com/en-us/dotnet/api/system.text.json?view=netcore-3.1).

I believe this is achievable in a rather straightforward fashion by separation of concerns. It will also enable many other scenarios, for example, pure validation without incurring the cost of building an entire AST.

Is this something that would be welcome? It may involve breaking changes (which means a major revision) so I prefer to ask before. I would also rather contribute and collaborate to maintain one project rather than forking my own version.

**Comment by springcomp** [comment]
That would be awesome and we would indeed welcome contributions on this front.
Please, share early work with us so we can discuss the interface between the main parser and the library-specific implementations.

**Comment by springcomp** [comment]
@jdevillard what your thoughts ?

**Comment by springcomp** [comment]
Currently the code makes heavy use of Newtonsoft.Json's `JToken` type.

Introducing any abstraction will therefore necessarily be a breaking change.

I think the JSON abstraction layer should use this type as its main interface. Making it an abstract class and have Newtonsoft.Json be the canonical implementation.

**Comment by springcomp** [comment]
Thanks a lot for your contribution.
