### ISSUE TITLE
Unable to install 1.0.145 from nuget due to missing JmesPath.Parser dependency

### ISSUE THREAD

**Issue by andrewdmoreno** [jdevillard/JmesPath.Net#28]
Trying to install version 1.0.145 from nuget results in an error as it lists JmesPath.Parser >= 1.0.0 as a dependency, but that library has not been published to nuget. 

https://www.nuget.org/packages/JmesPath.Net/1.0.145

https://www.nuget.org/packages/JmesPath.Parser/
Error 404 - Page Not Found
Looks like you might have gotten lost. Let's see if we can help you find your way!

**Comment by springcomp** [comment]
Thanks for reporting this.
