### ISSUE TITLE
Indexing an array

### ISSUE THREAD

**Issue by ZipZamZappem** [jdevillard/JmesPath.Net#3]
I want this:
[
  {
    "index": 0,
    "name": "a",
    "state": "up"
  },
  {
    "index": 1,
    "name": "b",
    "state": "down"
  },
  {
    "index": 2,
     "name": "c",
     "state": "up"
  }
]

From this:
{
  "people": [
    {
      "name": "a",
      "state": {"name": "up"}
    },
    {
      "name": "b",
      "state": {"name": "down"}
    },
    {
      "name": "c",
      "state": {"name": "up"}
    }
  ]
}

But there is no '@.index' to allow this to work:
    people[].{"index":@.index,"name":name, "state":state.name}

I realize this is not strictly a query function but AFAIK the items in a JSON list are ordered so it would not be arbitrary to associate a fixed index to each item.

Is there already a way to get this information?

**Comment by jdevillard** [comment]
Hello, 

this is not in the original specification but would be usefull.
@.index could not be an option because we can't have an index property in the JSON Source.

We will check what keyword we can add for this.

**Comment by ZipZamZappem** [comment]
A colleague suggested: 'offset'

**Comment by springcomp** [comment]
Thanks for the feedback.
I would first try an steer the official specification to include this before integrating non-official extensions.

**Comment by ZipZamZappem** [comment]
How does one go about proposing changes to the official specification?

**Comment by springcomp** [comment]
I think you must head over to [the official site](https://github.com/jmespath/jmespath.site) and write a pull request to the spec.
Similar to [this one](https://github.com/jmespath/jmespath.site/pull/21).
