### ISSUE TITLE
JmesPath syntax when there is a dot in key

### ISSUE THREAD

**Issue by neeraj9** [jdevillard/JmesPath.Net#32]
I have been trying to come up with appropriate JmesPath when there is a dot (".") in the key.

```json
{
  "some.key": 10
}
```

I am not sure how should I access the value for such or complex cases where the key has a dot.

**Comment by springcomp** [comment]
Hi @neeraj9, thank you for your feedback.
Your question is not specific to our .NET implementation and is more general to JmesPath itself.

Here is how you can achieve your goal: just wrap your key in double quotes.

![image](https://user-images.githubusercontent.com/8488398/105485910-e66e0680-5cad-11eb-87a4-aaefe5e2e693.png)

**Comment by neeraj9** [comment]
Thanks @springcomp thanks for the prompt revert. I made multiple attempts but could not do with you .NET library.

**Comment by springcomp** [comment]
@neeraj9 sorry for the misunderstanding. 

This must be a bug.
Thanks for reporting I will have a look.

**Comment by springcomp** [comment]
@neeraj9 I just tested with the current version and I cannot reproduce the bug.
![image](https://user-images.githubusercontent.com/8488398/105819917-23d9d900-5fb9-11eb-9dba-ec837767c822.png)

Please, can you share which version you have an issue with?

**Comment by springcomp** [comment]
@neeraj9, please feel free to reopen if you still experience any issue.
