### ISSUE TITLE
ERROR : Error(4, 76): syntax, near '$'. in C# when i Parse the expression

### ISSUE THREAD

**Issue by ImAbhishekTomar** [jdevillard/JmesPath.Net#36]
Hi, 

My expression is working fine with the online editor but when I used the same expression with the same data in c# it's giving me the below error.

- Version : JmesPath.Net - 1.0.153
- Framwork - Dot net core
- Language - C#

**ERROR**

Error(4, 76): syntax, near '$'.
   at DevLab.JmesPath.JmesPathScanner.yyerror(String format, Object[] args)
   at DevLab.JmesPath.JmesPathScanner.Scan()
   at DevLab.JmesPath.JmesPathScanner.yylex()
   at StarodubOleg.GPPG.Runtime.ShiftReduceParser`2.Parse()
   at DevLab.JmesPath.Parser.Parse(Stream stream, Encoding encoding, IJmesPathGenerator generator)
   at DevLab.JmesPath.JmesPath.Parse(Stream stream)
   at DevLab.JmesPath.JmesPath.Parse(String expression)
   at AzureFunctionDurableTic.AzureFunctionTIC.<DataFilter>d__16.MoveNext() in /Users/atomar10/Projects/AzureFunctionDurableTic/AzureFunctionDurableTic/AzureFunctionTIC.cs:line 203

**CODE**
```
            var q2 = @"
                            in_network[].{
                                                      unique_id:join('_',[negotiation_arrangement,name,billing_code_type,billing_code_type_version,billing_code,description,negotiated_rates[].tin | [0],negotiated_rates[].negotiated_price.expiration_date | [0],negotiated_rates[].negotiated_price.negotiated_type | [0]]),                 
                                                      reporting_entity_name:$.reporting_entity_name,
                                                      name:name,                   
                                                      billing_code:billing_code,                   
                                                      billing_code_type:billing_code_type,
                                                      billing_code_type_version:billing_code_type_version,                   
                                                      description:description,                   
                                                      negotiation_arrangement:negotiation_arrangement,    
                                                                     negotiated_rates:negotiated_rates[*].{
                                                                        providers:providers,
                                                                        tin:tin,
                                                                        service_code:service_code,
                                                                        expiration_date:negotiated_price.expiration_date,
                                                                        negotiated_rate:negotiated_price.negotiated_rate,
                                                                        negotiated_type:negotiated_price.negotiated_type
                                                                    }                 
                                                }";

            return q2;

  var jmes = new JmesPath();
  var exp = jmes.Parse(expression).Transform(data);
```

**Comment by jdevillard** [comment]
Hello, 

thanks for opening this issue, I would like to reproduce the issue. 
I understand that q2 seem to be the "transform expression" and it seems to be an parsing issue with some special characters.

Could you provide a sample input? or does it have sensitive information?
I would like to be sure what you meant using the "$" on your input.

**Comment by ImAbhishekTomar** [comment]
Sample JSON data

```
{
  "reporting_entity_name": "***********",
  "reporting_entity_type": "***********",
  "plan_name": "***********",
  "plan_id_type":  "***********",
  "plan_id": 1111,
  "plan_market_type":  "***********",
  "last_updated_on": "2021-08-30",
   "in_network" : [
        {
            "negotiation_arrangement" : "***********",
            "name" : "***********",
            "billing_code_type" : "***********",
            "billing_code_type_version" : "201",
            "billing_code" : "***********",
            "description" : "***********",
            "negotiated_rates" : [ {
            "providers" : [ 11111111,22222222,4444444,666666,777777,1111 ],
            "tin" : "***********",
            "service_code" : "***********-***********",
            "negotiated_price" : {
                "negotiated_type" : "***********",
                "negotiated_rate" : 10.000,
                "expiration_date" : "9999-12-31"
            }
            }]
        },
          {
            "negotiation_arrangement": "***********",
            "name": "***********",
            "billing_code_type": "***********",
            "billing_code_type_version": "201",
            "billing_code": "***********",
            "description": "***********",
            "negotiated_rates": [
              {
                "providers": [2342432, 234234, 243234, 234234, 24324, 424324234],
                "tin": "023432324324",
                "service_code": "***********-***********",
                "negotiated_price": {
                  "negotiated_type": "***********",
                  "negotiated_rate": 10.0,
                  "expiration_date": "9999-12-31"
                }
              }
            ]
          }
    ]
}
```

**Comment by jdevillard** [comment]
Thanks for this info and for providing the link to the tester.

The online tester you mention use the library available at  https://www.npmjs.com/package/@metrichor/jmespath

This library provide some extension for the initial spec like this one : 


**Root value access with $ symbol**
```
search({foo: {bar: 999}, baz: [1, 2, 3]}, '$.baz[*].[@, $.foo.bar]')

// OUTPUTS:
// [ [ 1, 999 ], [ 2, 999 ], [ 3, 999 ] ]
```

However, it could be a good idea to include this extensions in the .Net Specification.
We're currently checking with the team how specification could be extended and re-integrated in the initial spec to be sure that every language follow the same spec.

Thanks a lot.

**Comment by ImAbhishekTomar** [comment]
dose this package available for dot net core?  https://www.npmjs.com/package/@metrichor/jmespath

**Comment by jdevillard** [comment]
> Does this package available for dot net core? https://www.npmjs.com/package/@metrichor/jmespath or there is any workaround to access Root value?
> 
> ![Screenshot 2022-02-16 at 11 08 01 PM](https://user-images.githubusercontent.com/6933841/154323513-ec90a1a8-14c2-468c-9fc9-ee863e83a21a.png)

no it's specific to javascript implementation. 

We will see how to implement this as well on the dotnet version

**Comment by glenveegee** [comment]
Hey folks, The `$` symbol is definitely not standard JMESPath spec but there are a number of JMESPath libraries developed in the community that have extended the spec to include it because it's easy to implement and really useful. Another low hanging fruit that many folks implement (and you might consider) is a means to define custom functions.

**Comment by springcomp** [comment]
@glenveegee Thanks for the feedback.

`JmesPath.Net` does support custom functions. Please, look at [this repository](https://github.com/springcomp/JmesPath.Net.Functions) for samples. 

We plan to draft a JEP to submit a proposal that the official specification implements the `$` symbol.

**Comment by springcomp** [comment]
@ImAbhishekTomar A new version of JMESPath.NET [has been released](https://www.nuget.org/packages/JmesPath.Net/1.0.204).

It includes an implementation of [the `let()` function](https://github.com/jmespath-community/jmespath.spec/pull/72) that lets you capture any lexical scope you need for later use.

This may help you work around the non-standard `$` symbol.

You will need to register the `let()` function:

```c#
var parser = new JmesPath();
parser.FunctionRepository
    .Register<ItemsFunction>()
    .Register<ToObjectFunction>()
    .Register<ZipFunction>()
    .Register<LetFunction>()
    ;
```

The example you refer to can be written like so:

```
search( let({dollar: @}, &baz[*].[@, dollar.foo.bar]), {"foo": {"bar": 999}, "baz": [1, 2, 3]})
    -> [[1,999],[2,999],[3,999]]
```

Or, in C#

```
var document = "{\"foo\": {\"bar\": 999}, \"baz\": [1, 2, 3]}";
var expression = "let({dollar: @}, &baz[*].[@, dollar.foo.bar])";

var result = parser.Transform(document, expression);

Console.WriteLine(result);
```
