### ISSUE TITLE
Improve exception message

### ISSUE THREAD

**Issue by lorranpalmeira** [jdevillard/JmesPath.Net#4]
When is passed invalid filter the exception is very generic, maybe we can improve it.

Exception has occurred: CLR/Newtonsoft.Json.JsonReaderException
An exception of type 'Newtonsoft.Json.JsonReaderException' occurred in Newtonsoft.Json.dll but was not handled in user code: 'JsonToken EndArray is not valid for closing JsonType Object. Path ''

**Comment by jdevillard** [comment]
Thanks @lorranpalmeira to add this issues, will see how we can improve it using parser/lexer exception.

**Comment by springcomp** [comment]
@lorranpalmeira Please, could you share the context that led to the error you're seeing?
