### ISSUE TITLE
netstandard1.3

### ISSUE THREAD

**Issue by StefH** [jdevillard/JmesPath.Net#51]
I noticed that netstandard1.3 is removed as supported framework in this NuGet, can you please add this again?

**Comment by springcomp** [comment]
@StefH, previous versions of the [NuGet packages](https://www.nuget.org/packages/JmesPath.Net/1.0.125) that targetted netstandard1.3 should still work. 
What is a scenario you are having troubles with ?

**Comment by StefH** [comment]
I would like to keep up with your latest changes and I use your package in https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/WireMock.Net.csproj (which still supports netstandard1.3)

**Comment by springcomp** [comment]
@StefH I will reintroduce support.
If you want to speed things up, please submit a PR.
