### ISSUE TITLE
Secrets in the code

### ISSUE THREAD

**Issue by axdiamond** [jdevillard/JmesPath.Net#7]
Are these supposed to be committed to the repo? They look like secrets that shouldnt be exposed.
Forgive me if I'm mistaken, just trying to keep people safe.

https://github.com/jdevillard/JmesPath.Net/blob/master/appveyor.yml#L18

https://github.com/jdevillard/JmesPath.Net/blob/master/appveyor.yml#L20

https://github.com/jdevillard/JmesPath.Net/blob/master/appveyor.yml#L22

https://github.com/jdevillard/JmesPath.Net/blob/master/appveyor.yml#L57

**Comment by springcomp** [comment]
@axdiamond Thank you for your feedback.

This is how [AppVeyor works](https://www.appveyor.com/docs/how-to/secure-files/). Those secrets are store encrypted in the .yml file.
They have been encrypted by the owner of this repository @jdevillard. I, myself, am unable to decrypt those values.

Thanks for your concern.
