### ISSUE TITLE
Split into String

### ISSUE THREAD

**Issue by lorranpalmeira** [jdevillard/JmesPath.Net#8]
Hello @jdevillard ,
I think good ideia implements split into string.

What you think about?

**Comment by springcomp** [comment]
Thank you for the feedback.
This is a good idea for a separate function.

**Comment by springcomp** [comment]
This will make it easy to include third-party, unofficial functions.

**Comment by springcomp** [comment]
@lorranpalmeira I'm considering importing [this proposal](https://github.com/GorillaStack/jmespath.site/blob/master/docs/proposals/string-manipulation.rst) into the [JEPs](https://github.com/jmespath-unofficial/jmespath.jep) for discussion.

**Comment by springcomp** [comment]
`split()` is now part of the next iteration of the JMESPath Community specification.
