### ISSUE TITLE
Add extension point to register custom function implementation

### ISSUE THREAD

**Issue by NikiforovAll** [jdevillard/JmesPath.Net#81]
Hi,

I would like you to consider adding a feature to register a custom `JmesPathFunction`, so it is possible to use JMESPath in more advanced scenarios.

It could be something simple as constructor overload that exposes `Action<IRegisterFunctions>` as a parameter.

Roughly speaking:

```csharp
public JmesPath(Action<IRegisterFunctions> factory) {
  repository_ = JmesPathFunctionFactory.Create(evaluator_);
  factory.Invoke(repository_);
}
```

Please let me know if you accept contributions, I would be more than happy to add this feature.

**Comment by springcomp** [comment]
Thanks for your feedback.
Great news ! This feature is already implémented😀.

I agree this needs more / better documentation.
In the meantime, please look at the [compliance](https://github.com/jdevillard/JmesPath.Net/blob/master/tools/jmespathnet.compliance/Program.cs) tool to understand what is expected.

Also, you can look at my obsolete repository of [custom extensions](https://github.com/springcomp/JmesPath.Net.Functions) as a starting point for tours.

**Comment by NikiforovAll** [comment]
Thank you for the help and promptly reply.

**Comment by NikiforovAll** [comment]
ref: https://nikiforovall.github.io/dotnet/2023/01/08/jmespath-intro.html

**Comment by springcomp** [comment]
@NikiforovAll Thanks for the pointer.

We had actually touched on this feature in the official page.
https://jdevillard.github.io/JmesPath.Net/

For some reason, this page is not linked from the repository instructions.
