### ISSUE TITLE
Flatten operator should not produce an array with null elements

### ISSUE THREAD

**Issue by lodejard** [jdevillard/JmesPath.Net#9]
## Scenario
Using flatten operator `[]` or wildcard expression `[*]` on arrays, the result shouldn't contain elements which are null.

Starting with the the following json:
``` json
{"data":[null,["a",null,"b"],["c",["d",null,"e"],"f"]]}
```

## Expected
`data[]` produces:
``` json
["a","b","c",["d",null,"e"],"f"]
```
`data[*]` produces:
``` json
[["a",null,"b"],["c",["d",null,"e"],"f"]]
```
`map(&@,data)` produces:
``` json
[null,["a",null,"b"],["c",["d",null,"e"],"f"]]
```
## Actual
`data[]` produces:
``` json
[null,"a",null,"b","c",["d",null,"e"],"f"]
```
`data[*]` produces:
``` json
[null,["a",null,"b"],["c",["d",null,"e"],"f"]]
```
`map(&@,data)` is correct

**Comment by springcomp** [comment]
Yes, you are right.
Thanks for pointing this out.
