### ISSUE TITLE
JmesPath class might not be thread-safe

### ISSUE THREAD

**Issue by hell-racer** [jdevillard/JmesPath.Net#90]
If the `Transform()` is invoked on different json tokens, and expressions contain root-node expressions (`$.foo.bar`) it might lead to unexpected results, because the `evaluator_`'s `Root` property is updated inside `Transform()`/`Parse()` methods. Additional investigation needed.

**Comment by hell-racer** [comment]
I think I addressed it with #91.

**Comment by springcomp** [comment]
Cool. Thanks for the feedback.
