### ISSUE TITLE
C# Using JmesPath (1.0.308) Transform(string json, string expression) does not filter on integers when using `tick` delimiter.

### ISSUE THREAD

**Issue by Arrouusmith** [jdevillard/JmesPath.Net#97]
Querying this:

[
	{
		"Id": "ab9d98d3-f163-44b4-bb6a-739a82139208",
		"SupportCode": "031eb155-cc36-460a-ad6b-164f9b4fd0f8",
		"TicketNumber": 1
	}
]
with:

[?TicketNumber==\`1\`].SupportCode | [0]

In c# (dotNET 6.0) with lines:

var jmesPath = new JmesPath();
var result = jmesPath.Transform(json, expression);

results in null.

When running in the 'playground', the result is as shown below:

![image](https://github.com/jdevillard/JmesPath.Net/assets/130561447/97b4bf09-d733-4017-95d6-0e7169fc8635)

Thanks.

**Comment by springcomp** [comment]
Hi @Arrouusmith  I cannot reproduce this error

Can you double check with:

```jpnet.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JmesPath.Net" Version="1.0.308" />
  </ItemGroup>

</Project>
```

```Program.cs
using DevLab.JmesPath;

if (args.Length == 0)
{
    Console.Error.WriteLine("Missing required JMESPath expression.");
    Environment.Exit(42);
}

var expression = args[0];

var stdin = Console.In;
var stdout = Console.Out;

var text = stdin.ReadToEnd();

var jp = new JmesPath();
var token = jp.Transform(text, expression);

stdout.WriteLine(token);
```

And the following commands:

```pwsh
Set-Content -Path file.json -Value '[{"Id":"ab9d98d3-f163-44b4-bb6a-739a82139208","SupportCode":"031eb155-cc36-460a-ad6b-164f9b4fd0f8","TicketNumber":1}]'
cat file.json | dotnet run -- "[?TicketNumber==``1``].SupportCode | [0]"
```

**Comment by Arrouusmith** [comment]
Hi, yes, you are quite right. I have gone back through my system and found that I have been corrupting the format of the string immediately before running the expression over it. My bad and thank you for your time.
